### ISSUE TITLE
为什么不用github pages 来建立备份了？

### ISSUE THREAD

**Issue by zhou18520786640** [dsxNiubility/SXTEMPDATA#1]
十分感谢你的技术分享，让我学到很多东西，看到您是使用pdf备份。为什么不考虑github pages 来备份，即方便修改 同时方便技术的传播

**Comment by dsxNiubility** [comment]
pdf的确不好，所以后面就没用pdf了啊。 没有实时修改的需求，就是往里面备份一下罢了，就没有pages什么的了

**Comment by zhou18520786640** [comment]
谢谢
